name: tests
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ci image
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_ACCESS_TOKEN }}
      - run: docker build -t ${{ secrets.DH_USERNAME }}/aiocircuitbreaker:ci-$GITHUB_RUN_NUMBER -f ./Dockerfile .
      - run: docker push ${{ secrets.DH_USERNAME }}/aiocircuitbreaker:ci-$GITHUB_RUN_NUMBER
  
  check-format:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm -i -w /tmp -v $(pwd):/tmp ${{ secrets.DH_USERNAME }}/aiocircuitbreaker:ci-$GITHUB_RUN_NUMBER make format

  tests:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm -i -w /tmp -v $(pwd):/tmp ${{ secrets.DH_USERNAME }}/aiocircuitbreaker:ci-$GITHUB_RUN_NUMBER make test-with-coverage-xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          verbose: true
